
//Modelo JSON
export var Materias_1804 = {
  "Plan": "Plan 18.04, Lic. en Biologia con Orientacion en Ecología",
  "Materias" : [
    {
    "Ubicacion_en_el_array": 0,
    "Nombre": "Elementos de Matematica",
    "Numero": 10014,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 9,
    "Horas_Totales": 144
    },
    {
    "Ubicacion_en_el_array": 1,
    "Nombre": "Elementos de Quimica",
    "Numero": 10015,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 2,
    "Nombre": "Biologia General I",
    "Numero": 11084,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 3,
    "Nombre": "Estudio de la Constitución Nacional y los Derechos Humanos",
    "Numero": 20038,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Ambos",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 4,
    "Nombre": "Análisis Matemático I",
    "Numero": 10022,
    "Hecha": false,
    "Requiere": [10014],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "II",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 5,
    "Nombre": "Quimica I",
    "Numero": 11933,
    "Hecha": false,
    "Requiere": [10015],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "II",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 6,
  "Nombre": "Álgebra",
  "Numero": 10021,
  "Hecha": false,
  "Requiere": [10014],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "II",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 7,
  "Nombre": "Biologia General II",
  "Numero": 11035,
  "Hecha": false,
  "Requiere": [11084],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "III",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 8,
  "Nombre": "Ciencias de la Tierra, del Agua y de la Atmósfera",
  "Numero": 11201,
  "Hecha": false,
  "Requiere": [11933],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "III",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 9,
  "Nombre": "Metodología de la Investigación",
  "Numero": 23001,
  "Hecha": false,
  "Requiere": [11084],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "III",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 10,
  "Nombre": "Física I",
  "Numero": 10908,
  "Hecha": false,
  "Requiere": [10022, 10021],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "III",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 11,
  "Nombre": "Física II",
  "Numero": 10909,
  "Hecha": false,
  "Requiere": [10908],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "IV",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 12,
  "Nombre": "Química II",
  "Numero": 11906,
  "Hecha": false,
  "Requiere": [11933],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "IV",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 13,
  "Nombre": "Biología de protistos, hongos y briofitas",
  "Numero": 11037,
  "Hecha": false,
  "Requiere": [11035],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "IV",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 14,
  "Nombre": "Estadística I",
  "Numero": 11974,
  "Hecha": false,
  "Requiere": [10014],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "IV",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 15,
  "Nombre": "Química III",
  "Numero": 11963,
  "Hecha": false,
  "Requiere": [11906,11035],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "V",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 16,
  "Nombre": "Botánica I",
  "Numero": 11038,
  "Hecha": false,
  "Requiere": [11035],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "V",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 17,
  "Nombre": "Biología Animal I (Invertebrados parte I)",
  "Numero": 11107,
  "Hecha": false,
  "Requiere": [11035],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "V",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 18,
  "Nombre": "Biología Animal II (Vertebrados parte I)",
  "Numero": 11108,
  "Hecha": false,
  "Requiere": [11035],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "V",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 19,
  "Nombre": "Genética",
  "Numero": 11202,
  "Hecha": false,
  "Requiere": [11035],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 20,
  "Nombre": "Teoría General de Sistemas",
  "Numero": 10204,
  "Hecha": false,
  "Requiere": ["Ninguna"],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 21,
  "Nombre": "Ecología I",
  "Numero": 11208,
  "Hecha": false,
  "Requiere": [11035, 11201],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 22,
  "Nombre": "Ética",
  "Numero": 31002,
  "Hecha": false,
  "Requiere": [20038],
  "Disponible": false,
  "Cuatrimestre": "Ambos",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 23,
  "Nombre": "Inglés I (**)",
  "Numero": 31971,
  "Hecha": false,
  "Requiere": ["Ninguna"],
  "Disponible": false,
  "Cuatrimestre": "Ambos",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 24,
  "Nombre": "Computación (**)",
  "Numero": 11964,
  "Hecha": false,
  "Requiere": ["Ninguna"],
  "Disponible": false,
  "Cuatrimestre": "Ambos",
  "Cuatrimestre_Perteneciente": "VI",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 25,
  "Nombre": "Estadística II",
  "Numero": 11975,
  "Hecha": false,
  "Requiere": [31971, 11964, 11974],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "VII",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 26,
  "Nombre": "Evolución",
  "Numero": 11241,
  "Hecha": false,
  "Requiere": [31971, 11964, 11202, 11208, 11037, 11108, 11107],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "VII",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 27,
  "Nombre": "Ecología II",
  "Numero": 11209,
  "Hecha": false,
  "Requiere": [31971, 11964, 11208],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "VII",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 28,
  "Nombre": "Instrumentación Biológica",
  "Numero": 11040,
  "Hecha": false,
  "Requiere": [31971, 11964, 11933, 11208],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "VII",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 29,
  "Nombre": "Ecología III",
  "Numero": 11210,
  "Hecha": false,
  "Requiere": [31971, 11964, 11208, 10204],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VII",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 30,
  "Nombre": "Botánica II",
  "Numero": 11039,
  "Hecha": false,
  "Requiere": [31971, 11964, 11038],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VIII",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 31,
  "Nombre": "Biología Animal III (Invertebrados parte II)",
  "Numero": 11109,
  "Hecha": false,
  "Requiere": [31971, 11964, 11107],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VIII",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 32,
  "Nombre": "Biología Animal IV (Vertebrados parte II)",
  "Numero": 11110,
  "Hecha": false,
  "Requiere": [31971, 11964, 11108],
  "Disponible": false,
  "Cuatrimestre": "Segundo",
  "Cuatrimestre_Perteneciente": "VIII",
  "Horas_Semanales": 6,
  "Horas_Totales": 96
  },
  {
  "Ubicacion_en_el_array": 33,
  "Nombre": "Fisiología Animal",
  "Numero": 10203,
  "Hecha": false,
  "Requiere": [31971, 11964, 10909, 11107, 11110, 11963],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "IX",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 34,
  "Nombre": "Ecotoxicología",
  "Numero": 11042,
  "Hecha": false,
  "Requiere": [31971, 11964, 11963, 11208],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "IX",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 35,
  "Nombre": "Fisiología Vegetal",
  "Numero": 10080,
  "Hecha": false,
  "Requiere": [31971, 11964, 10909, 11202, 11039],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "IX",
  "Horas_Semanales": 8,
  "Horas_Totales": 128
  },
  {
  "Ubicacion_en_el_array": 36,
  "Nombre": "Inglés II (*)",
  "Numero": 31972,
  "Hecha": false,
  "Requiere": [31971],
  "Disponible": false,
  "Cuatrimestre": "Ambos",
  "Cuatrimestre_Perteneciente": "IX",
  "Horas_Semanales": 4,
  "Horas_Totales": 64
  },
  {
  "Ubicacion_en_el_array": 37,
  "Nombre": "Ciclo de Asignaturas y/o Actividades Optativas",
  "Numero": 10217,
  "Hecha": false,
  "Requiere": [10014, 10015, 11084, 20038, 10022, 11933, 10021, 11035, 11201, 23001, 10908, 10909, 11906, 11037, 11974, 11963, 11038, 11107, 11108, 11202, 10204],
  "Disponible": false,
  "Cuatrimestre": "Primero",
  "Cuatrimestre_Perteneciente": "IX",
  "Horas_Semanales": 0,
  "Horas_Totales": 0
  },
  {
  "Ubicacion_en_el_array": 38,
  "Nombre": "Tesis de Grado",
  "Numero": 101,
  "Hecha": false,
  "Requiere": [10217, 10203, 11042, 10080, 31972],
  "Disponible": false,
  "Cuatrimestre": "Ambos",
  "Cuatrimestre_Perteneciente": "",
  "Horas_Semanales": 0,
  "Horas_Totales": 0
  }
  ]
  };
