
//Modelo JSON
export var Materias_4803 = {
  "Plan": "Plan 48.03, Profesorado en Biologia",
  "Materias" : [
    {
    "Ubicacion_en_el_array": 0,
    "Nombre": "Elementos de Matematica",
    "Numero": 10014,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 9,
    "Horas_Totales": 144
    },
    {
    "Ubicacion_en_el_array": 1,
    "Nombre": "Elementos de Quimica",
    "Numero": 10015,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 2,
    "Nombre": "Biologia General I",
    "Numero": 11084,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 3,
    "Nombre": "Introducción a la Problemática Educacional",
    "Numero": 30057,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 4,
    "Nombre": "Quimica I",
    "Numero": 11933,
    "Hecha": false,
    "Requiere": [10015],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "II",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 5,
    "Nombre": "Análisis Matemático I",
    "Numero": 10022,
    "Hecha": false,
    "Requiere": [10014],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "II",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 6,
    "Nombre": "Estudio de la Constitución Nacional y los Derechos Humanos",
    "Numero": 20038,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Ambos",
    "Cuatrimestre_Perteneciente": "I",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 7,
    "Nombre": "Competencias en Informática (*)",
    "Numero": 19054,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Ambos",
    "Cuatrimestre_Perteneciente": "",
    "Horas_Semanales": 0,
    "Horas_Totales": 0
    },
    {
    "Ubicacion_en_el_array": 8,
    "Nombre": "Competencias en Inglés (*)",
    "Numero": 39541,
    "Hecha": false,
    "Requiere": ["Ninguna"],
    "Disponible": false,
    "Cuatrimestre": "Ambos",
    "Cuatrimestre_Perteneciente": "",
    "Horas_Semanales": 0,
    "Horas_Totales": 0
    },
    {
    "Ubicacion_en_el_array": 9,
    "Nombre": "Biologia General II",
    "Numero": 11035,
    "Hecha": false,
    "Requiere": [11084],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "III",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 10,
    "Nombre": "Psicología del Aprendizaje",
    "Numero": 30105,
    "Hecha": false,
    "Requiere": [30057],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "III",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 11,
    "Nombre": "Física",
    "Numero": 10908,
    "Hecha": false,
    "Requiere": [10022],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "III",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 12,
    "Nombre": "Ciencias de la Tierra, del Agua y de la Atmósfera",
    "Numero": 11201,
    "Hecha": false,
    "Requiere": [11933],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "III",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 13,
    "Nombre": "Didáctica General",
    "Numero": 34101,
    "Hecha": false,
    "Requiere": [30057],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "III",
    "Horas_Semanales": 4,
    "Horas_Totales": 84
    },
    {
    "Ubicacion_en_el_array": 14,
    "Nombre": "Química II",
    "Numero": 11906,
    "Hecha": false,
    "Requiere": [11933],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "IV",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 15,
    "Nombre": "Biología de protistos, hongos y briofitas",
    "Numero": 11037,
    "Hecha": false,
    "Requiere": [11035],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "IV",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 16,
    "Nombre": "Estadística I",
    "Numero": 11974,
    "Hecha": false,
    "Requiere": [10014],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "IV",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 17,
    "Nombre": "Política Educacional",
    "Numero": 34103,
    "Hecha": false,
    "Requiere": [30057],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "IV",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 18,
    "Nombre": "Química III",
    "Numero": 11963,
    "Hecha": false,
    "Requiere": [11906,11035,19054, 39541],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "V",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 19,
    "Nombre": "Botánica I",
    "Numero": 11038,
    "Hecha": false,
    "Requiere": [19054, 39541,11035],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "V",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 20,
    "Nombre": "Biología Animal I (Invertebrados parte I)",
    "Numero": 11107,
    "Hecha": false,
    "Requiere": [19054, 39541,11035],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "V",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 21,
    "Nombre": "Biología Animal II (Vertebrados parte I)",
    "Numero": 11108,
    "Hecha": false,
    "Requiere": [19054, 39541,11035],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "V",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 22,
    "Nombre": "Metodología de la Investigación",
    "Numero": 23001,
    "Hecha": false,
    "Requiere": [19054, 39541,11084],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "V",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 23,
    "Nombre": "Genética",
    "Numero": 11202,
    "Hecha": false,
    "Requiere": [19054, 39541,11035],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VI",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 24,
    "Nombre": "Ecología I",
    "Numero": 11208,
    "Hecha": false,
    "Requiere": [19054, 39541,11035, 11201],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VI",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 25,
    "Nombre": "Ética",
    "Numero": 31002,
    "Hecha": false,
    "Requiere": [19054, 39541,20038],
    "Disponible": false,
    "Cuatrimestre": "Ambos",
    "Cuatrimestre_Perteneciente": "VI",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 26,
    "Nombre": "Didáctica de las Ciencias Biológicas",
    "Numero": 34801,
    "Hecha": false,
    "Requiere": [19054, 39541,23001, 34101, 30105],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VI",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 27,
    "Nombre": "Educación Ambiental",
    "Numero": 20257,
    "Hecha": false,
    "Requiere": [19054, 39541,34101, 23001, 30105],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VI",
    "Horas_Semanales": 4,
    "Horas_Totales": 64
    },
    {
    "Ubicacion_en_el_array": 28,
    "Nombre": "Prácticas Docentes I",
    "Numero": 34802,
    "Hecha": false,
    "Requiere": [19054, 39541,34801],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "VII",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 29,
    "Nombre": "Biología celular y molecular I ",
    "Numero": 11043,
    "Hecha": false,
    "Requiere": [19054, 39541,11202, 11963],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "VII",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 30,
    "Nombre": "Fisiología General",
    "Numero": 14801,
    "Hecha": false,
    "Requiere": [19054, 39541,11107, 11108, 11038],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "VII",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 31,
    "Nombre": "Psicosociología de los Grupos e Instituciones Educativas",
    "Numero": 30018,
    "Hecha": false,
    "Requiere": [19054, 39541,30105, 34103, 34101],
    "Disponible": false,
    "Cuatrimestre": "Primero",
    "Cuatrimestre_Perteneciente": "VII",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 32,
    "Nombre": "Evolución",
    "Numero": 11241,
    "Hecha": false,
    "Requiere": [19054, 39541,11202, 11208, 11037, 11108, 11107],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VIII",
    "Horas_Semanales": 8,
    "Horas_Totales": 128
    },
    {
    "Ubicacion_en_el_array": 33,
    "Nombre": "Biología Humana y Salud",
    "Numero": 14802,
    "Hecha": false,
    "Requiere": [19054, 39541,11108],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VIII",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    },
    {
    "Ubicacion_en_el_array": 34,
    "Nombre": "Prácticas Docentes II",
    "Numero": 34803,
    "Hecha": false,
    "Requiere": [19054, 39541,34802, 30018],
    "Disponible": false,
    "Cuatrimestre": "Segundo",
    "Cuatrimestre_Perteneciente": "VIII",
    "Horas_Semanales": 6,
    "Horas_Totales": 96
    }
    ]
    };
